---

# notes
# ports are exposed to the host machine
# exposed only allows access by linked services
#
# EXAMPLE DEPLOYS
# https://gist.github.com/Webreaper/81ecda3ecc45fa61a16dfc90cfc4550d
# EXAMPLE DEPLOYS

# CAP_ADD/DROP information: http://rhelblog.redhat.com/2016/10/17/secure-your-containers-with-this-one-weird-trick/

# @TODO: wireguard, flexget, git server, backblaze, anonaddy
# @TODO review these https://teddit.net/r/radarr/comments/hbwnb2/a_list_of_all_companion_tools_and_software/
# @TODO actually restrict networks
# @TODO try https://dockersl.im

# p2p related apps: https://teddit.net/r/radarr/comments/hbwnb2/a_list_of_all_companion_tools_and_software/
#


version: "2.4"

services:

  proxy:
    # @TODO split into two containers
    # >> https://github.com/nginx-proxy/nginx-proxy#separate-containers
    # alpine container
    image: jwilder/nginx-proxy:latest
    #read_only: true
    container_name: proxy
    networks:
      - proxy
      - vpn
      - bazarr
      - jackett
      - ombi
      - organizr
      - plex
      - radarr
      - sonarr
      - transmission-movies
      - transmission-tv
      - transmission-books
      - whoami
    environment:
      - NETWORK_ACCESS=internal
      - DEFAULT_HOST=whoami.erdos.local
    ports:
      - 80:80
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
        #tmpfs:
        #  - /var/cache/nginx/client_temp
        #  - /var/cache/nginx/proxy_temp
        #  - /var/cache/nginx/fastcgi_temp
        #  - /var/cache/nginx/uwsgi_temp
        #  - /var/cache/nginx/scgi_temp
        #  - /etc/nginx/dhparam
        #  - /etc/nginx/conf.d
        #  - /var/run
        #  - /tmp
        #cap_drop:
        #  - ALL
        #cap_add:
        #  - CHOWN
        #  - NET_BIND_SERVICE
        #  - SETGID
        #  - SETUID

  whoami:
    # alpine
    image: "jwilder/whoami:latest"
    container_name: whoami
    read_only: true
    cap_drop:
      - ALL
    networks:
      - proxy
      - whoami
    expose:
      - 8000
    user: nobody
    environment:
      - NETWORK_ACCESS=internal
      - VIRTUAL_HOST=whoami.erdos.local
      - VIRTUAL_PORT=8000


  transmission-movies:
    container_name: transmission-movies
    # alpine
    image: lscr.io/linuxserver/transmission:latest
    networks:
      - proxy
      - transmission-movies
      - jackett
    restart: always
    cap_drop:
      - ALL
    cap_add:
      - SETUID
      - SETGID
      - CHOWN
    environment:
      - NETWORK_ACCESS=internal
      - S6_READ_ONLY_ROOT=1
      - PUID=64999
      - PGID=64999
      - VIRTUAL_HOST=movies.erdos.local
      - VIRTUAL_PORT=9091
    expose:
      - "9091" # webui
    ports:
      - "58320:51413/tcp" # p2p traffic
      - "58320:51413/udp" # p2p traffic
    volumes:
      - /volume1/docker_app_data/apps/transmission-movies/config:/config
      - /volume1/docker_app_data/apps/transmission-movies/media:/downloads/complete
      - transmission-movies-downloads-incomplete:/downloads/incomplete
    tmpfs:
      - /var/run/s6:rw,exec
  
  
  transmission-tv:
    container_name: transmission-tv
    # alpine
    image: lscr.io/linuxserver/transmission:latest
    cap_drop:
      - ALL
    cap_add:
      - SETUID
      - SETGID
      - CHOWN
    networks:
      - proxy
      - transmission-tv
    restart: always
    environment:
      - NETWORK_ACCESS=internal
      - S6_READ_ONLY_ROOT=1
      - PUID=64999
      - PGID=64999
      - VIRTUAL_HOST=tv.erdos.local
      - VIRTUAL_PORT=9091
    expose:
      - "9091" # webui
    ports:
      - "55880:51413/tcp" # p2p traffic
      - "55880:51413/udp" # p2p traffic
    volumes:
      - /volume1/docker_app_data/apps/transmission-tv/config:/config
      - /volume1/docker_app_data/apps/transmission-tv/media:/downloads/complete
      - transmission-tv-downloads-incomplete:/downloads/incomplete
    tmpfs:
      - /var/run/s6:rw,exec

  

  transmission-books:
    container_name: transmission-books
    # alpine
    image: lscr.io/linuxserver/transmission:latest
    cap_drop:
      - ALL
    cap_add:
      - SETUID
      - SETGID
      - CHOWN
    networks:
      - proxy
      - transmission-books
    restart: always
    environment:
      - NETWORK_ACCESS=internal
      - S6_READ_ONLY_ROOT=1
      - PUID=64999
      - PGID=64999
      - VIRTUAL_HOST=books.erdos.local
      - VIRTUAL_PORT=9091
    expose:
      - 9091 # webui
    ports:
      - "41414:51413/tcp" # p2p traffic
      - "41414:51413/udp" # p2p traffic
    volumes:
      - /volume1/docker_app_data/apps/transmission-books/config:/config
      - /volume1/docker_app_data/apps/transmission-books/media:/downloads/complete
      - transmission-books-downloads-incomplete:/downloads/incomplete
    tmpfs:
      - /var/run/s6:rw,exec



  # movie player
  # @TODO try to put this in bridge networking?
  plex:
    container_name: plex
    image: lscr.io/linuxserver/plex:latest
    network_mode: host
    cap_drop:
      - ALL
    cap_add:
      - SETGID
      - SETUID
      - CHOWN
    environment:
      - NETWORK_ACCESS=internal
      - S6_READ_ONLY_ROOT=1 # https://github.com/just-containers/s6-overlay/pull/176
      - PUID=64999
      - PGID=64999
      - VERSION=docker
      - ADVERTISE_IP=http://10.0.1.10:32400/
    volumes:
      - /volume1/docker_app_data/apps/plex/config:/config
      - /volume1/docker_app_data/apps/transmission-tv/media:/tv:ro
      - /volume1/docker_app_data/apps/transmission-movies/media:/movies:ro
    tmpfs:
      - /var/run/s6:exec
      - /app
      - /defaults


  # Manages your movie library
  # @TODO pin down basic hardening
  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    networks:
      - proxy
      - radarr
      - jackett
      - transmission-movies
    cap_drop:
      - ALL
    cap_add:
      - SETUID
      - SETGID
      - CHOWN
    environment:
      - NETWORK_ACCESS=internal
      - S6_READ_ONLY_ROOT=1 # https://github.com/just-containers/s6-overlay/pull/176
      - PUID=64999
      - PGID=64999
      - TZ=Europe/London
      - VIRTUAL_HOST=radarr.erdos.local
      - VIRTUAL_PORT=7878
    volumes:
      - /volume1/docker_app_data/apps/raddarr/config:/config
      - /volume1/docker_app_data/apps/transmission-movies/media:/movies:ro
      - /volume1/docker_app_data/apps/transmission-movies/media:/downloads/complete:ro
    expose:
      - 7878 
    restart: unless-stopped


  # Manages your TV library
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    networks:
      - proxy
      - sonarr
      - jackett
      - transmission-tv
    cap_drop:
      - ALL
    cap_add:
      - SETUID
      - SETGID
      - CHOWN
    environment:
      - NETWORK_ACCESS=internal
      - S6_READ_ONLY_ROOT=1 # https://github.com/just-containers/s6-overlay/pull/176
      - PUID=64999
      - PGID=64999
      - TZ=Europe/London
      - VIRTUAL_HOST=sonarr.erdos.local
      - VIRTUAL_PORT=8989
    volumes:
      - /volume1/docker_app_data/apps/sonarr/config:/config
      - /volume1/docker_app_data/apps/transmission-tv/media:/tv:ro
      - /volume1/docker_app_data/apps/transmission-tv/media:/downloads/complete:ro
    expose:
      - 8989
    restart: unless-stopped


  jackett:
    image: lscr.io/linuxserver/jackett:latest
    container_name: jackett
    volumes:
      - /volume1/docker_app_data/apps/jackett/config:/config
    networks:
      - proxy
      - jackett
      - sonarr
      - radarr
    cap_drop:
      - ALL
    cap_add:
      - SETUID
      - SETGID
      - CHOWN
    environment:
      - S6_READ_ONLY_ROOT=1
      - NETWORK_ACCESS=internal
      - PUID=64999
      - PGID=64999
      - TZ=Europe/London
      - AUTO_UPDATE=true #optional
      - VIRTUAL_HOST=jackett.erdos.local
      - VIRTUAL_PORT=9117
    expose: 
      - 9117


  bazarr:
    image: lscr.io/linuxserver/bazarr:latest
    container_name: bazarr
    cap_drop:
      - ALL
    cap_add:
      - SETUID
      - SETGID
      - CHOWN
    networks:
      - proxy
      - bazarr
    environment:
      - S6_READ_ONLY_ROOT=1
      - NETWORK_ACCESS=internal
      - PUID=64999
      - PGID=64999
      - TZ=Europe/London
      - VIRTUAL_HOST=bazarr.erdos.local
      - VIRTUAL_PORT=6767
    volumes:
      - /volume1/docker_app_data/apps/bazarr/config:/config
      - /volume1/docker_app_data/apps/transmission-tv/media:/tv
      - /volume1/docker_app_data/apps/tranmission-movies/media:/movies
    expose:
      - 6767
    restart: always


  ombi:
    #image: lscr.io/linuxserver/ombi
    image: linuxserver/ombi:latest
    container_name: ombi
    cap_drop:
      - ALL
    cap_add:
      - SETUID
      - SETGID
      - CHOWN
    networks: 
      - ombi
      - proxy
    environment:
      - S6_READ_ONLY_ROOT=1
      - NETWORK_ACCESS=internal
      - PUID=64999
      - PGID=64999
      - TZ=Europe/London
        #- BASE_URL=/ombi #optional
      - VIRTUAL_HOST=ombi.erdos.local
      - VIRTUAL_PORT=3579
    volumes:
      - /volume1/docker_app_data/apps/ombi/config:/config
    expose: 
      - 3579
    restart: unless-stopped

#  organizr:
#    # alpine
#    image: organizr/organizr:latest
#    container_name: organizr
#    cap_drop:
#      - ALL
#    cap_add:
#      - SETUID
#      - SETGID
#      - CHOWN
#    networks:
#      - organizr
#      - proxy
#      - sonarr
#    environment:
#      - S6_READ_ONLY_ROOT=1
#      - VIRTUAL_HOST=organizr.erdos.local,org.erdos.local
#      - VIRTUAL_PORT=80
#      - NETWORK_ACCESS=internal
#      - PUID=64999
#      - PGID=64999
#    expose:
#      - 80
#    volumes:
#      - /config




# @TODO
# ADD THIS SERVICE
# ADD THIS SERVICE
# Traktarr: Add content to Radarr/Sonarr from Trakt.tv
# https://hub.docker.com/r/containrrr/watchtower
# organizr/organizr
# ADD THIS SERVICE
# ADD THIS SERVICE
# @TODO


volumes:
  transmission-movies-downloads-incomplete:
  transmission-tv-downloads-incomplete:
  transmission-books-downloads-incomplete:

  transmission-vpn-movies-downloads-incomplete:
  transmission-vpn-tv-downloads-incomplete:

  # BOBARR
  web_build:
  api_build:
  api_node_modules:
  web_node_modules:
  db_data:
  redis_data:
  # BOBARR

networks:
  transmission-movies:
  transmission-tv:
  transmission-books:
  jackett:
  sonarr:
  radarr:
  organizr:
    #plex:
  wireguard:
  transmission-vpn-movies:
  transmission-vpn-tv:
  proxy:
  whoami:
  plex:
  bazarr:
  ombi:
  vpn:
