---

# notes
# ports are exposed to the host machine
# exposed only allows access by linked services
#
# EXAMPLE DEPLOYS
# https://gist.github.com/Webreaper/81ecda3ecc45fa61a16dfc90cfc4550d
# EXAMPLE DEPLOYS

# CAP_ADD/DROP information: http://rhelblog.redhat.com/2016/10/17/secure-your-containers-with-this-one-weird-trick/

# @TODO: wireguard, flexget, git server, backblaze, anonaddy

# p2p related apps: https://teddit.net/r/radarr/comments/hbwnb2/a_list_of_all_companion_tools_and_software/

version: "2.4"

services:

  nginx-proxy:
    image: jwilder/nginx-proxy
    container_name: proxy
    ports:
      - "8080:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro

  whoami:
    image: jwilder/whoami
    container_name: whoami
    environment:
      - VIRTUAL_HOST=whoami.erdos.local

  transmission-movies:
    container_name: transmission-movies
    image: lscr.io/linuxserver/transmission:latest
    #network_mode: service:temp_expressvpn
    networks:
      - transmission-movies
    restart: always
    read_only: true
    environment:
      - S6_READ_ONLY_ROOT=1
      - PUID=64999
      - PGID=64999
    ports:
      - "49091:9091/tcp"   # webui
      - "41412:51413/tcp" # p2p traffic
      - "41412:51413/udp" # p2p traffic
    volumes:
      - /docker/data/transmission-movies:/config
      - /docker/media/movies:/downloads/complete
      - transmission-movies-downloads-incomplete:/downloads/incomplete
    tmpfs:
      - /var:rw,exec
  
  
  transmission-tv:
    container_name: transmission-tv
    image: lscr.io/linuxserver/transmission:latest
    networks:
      - transmission-tv
    restart: always
    read_only: true
    environment:
      - S6_READ_ONLY_ROOT=1
      - PUID=64999
      - PGID=64999
    ports:
      - "49092:9091/tcp"   # webui
      - "41413:51413/tcp" # p2p traffic
      - "41413:51413/udp" # p2p traffic
    volumes:
      - /docker/data/transmission-tv:/config
      - /docker/media/tv:/downloads/complete
      - transmission-tv-downloads-incomplete:/downloads/incomplete
    tmpfs:
      - /var:rw,exec
  
  
  transmission-books:
    container_name: transmission-books
    image: lscr.io/linuxserver/transmission:latest
    #network_mode: "service:gluetun"
    #networks:
    #  - vpn
    #- transmission-books
    restart: always
    #read_only: true
    environment:
      - S6_READ_ONLY_ROOT=1
      - PUID=64999
      - PGID=64999
        #ports:
        #  - "49093:9091/tcp"   # webui
        #  - "41414:51413/tcp" # p2p traffic
        #  - "41414:51413/udp" # p2p traffic
    volumes:
      - /docker/data/transmission-books:/config
      - /docker/media/books:/downloads/complete
      - transmission-books-downloads-incomplete:/downloads/incomplete
    tmpfs:
      - /var:rw,exec
  
  
  # movie player
  plex:
    container_name: plex
    image: lscr.io/linuxserver/plex:latest
    network_mode: host
    restart: always
    environment:
      - S6_READ_ONLY_ROOT=1 # https://github.com/just-containers/s6-overlay/pull/176
      - PUID=64999
      - PGID=64999
      - VERSION=docker
      - ADVERTISE_IP=http://10.0.1.20:32400/
    volumes:
      - /docker/data/plex/database:/config
      - /docker/media/tv:/downloaded_media/tv:ro
      - /docker/media/movies:/downloaded_media/movies:ro
    tmpfs:
      - /var:rw,exec
      - /transcode:ro

  # Manages your movie library
  radarr:
    image: lscr.io/linuxserver/radarr
    container_name: radarr
    networks:
      - radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    ports:
      - 7878:7878
    restart: unless-stopped


  # Manages your TV library
  sonarr:
    image: lscr.io/linuxserver/sonarr
    container_name: sonarr
    networks:
      - sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    ports:
      - 8989:8989
    restart: unless-stopped


  organizr:
    image: organizr/organizr
    container_name: organizer
    #environment:
    #- fpm=false
        #- branch="v2-master"
    ports:
      - 5656:80

  jackett:
    image: lscr.io/linuxserver/jackett
    container_name: jackett
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      - AUTO_UPDATE=true #optional
        #- RUN_OPTS=<run options here> #optional
    #volumes:
    #  - <path to data>:/config
    #  - <path to blackhole>:/downloads
    ports:
      - 9117:9117
    restart: unless-stopped




volumes:
  transmission-movies-downloads-incomplete:
  transmission-tv-downloads-incomplete:
  transmission-books-downloads-incomplete:

  transmission-vpn-movies-downloads-incomplete:
  transmission-vpn-tv-downloads-incomplete:

  # BOBARR
  web_build:
  api_build:
  api_node_modules:
  web_node_modules:
  db_data:
  redis_data:
  # BOBARR

networks:
  transmission-movies:
  transmission-tv:
  transmission-books:
  jackett:
  sonarr:
  radarr:
  plex:
  wireguard:
  transmission-vpn-movies:
  transmission-vpn-tv:

