---

# notes
# ports are exposed to the host machine
# exposed only allows access by linked services
#
# EXAMPLE DEPLOYS
# https://gist.github.com/Webreaper/81ecda3ecc45fa61a16dfc90cfc4550d
# EXAMPLE DEPLOYS

# CAP_ADD/DROP information: http://rhelblog.redhat.com/2016/10/17/secure-your-containers-with-this-one-weird-trick/

# @TODO: wireguard, flexget, git server, backblaze, anonaddy
# @TODO review these https://teddit.net/r/radarr/comments/hbwnb2/a_list_of_all_companion_tools_and_software/
# @TODO actually restrict networks

# p2p related apps: https://teddit.net/r/radarr/comments/hbwnb2/a_list_of_all_companion_tools_and_software/
#


version: "2.4"

services:

  proxy:
    # @TODO split into two containers
    # >> https://github.com/nginx-proxy/nginx-proxy#separate-containers
    # alpine container
    image: jwilder/nginx-proxy@sha256:860110839a309c4da3a915f53c2f3e5e99da9c9d3ea80c05a4155be2df1412ed
    read_only: true
    container_name: proxy
    networks:
      - whoami
      - transmission-movies
      - transmission-tv
      - transmission-books
      - plex
      - radarr
      - sonarr
      - organizr
      - jackett
      - bazarr
      - ombi
    environment:
      - NETWORK_ACCESS=internal
      - DEFAULT_HOST=whoami.erdos.local
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
    tmpfs:
      - /var/cache/nginx/client_temp
      - /var/cache/nginx/proxy_temp
      - /var/cache/nginx/fastcgi_temp
      - /var/cache/nginx/uwsgi_temp
      - /var/cache/nginx/scgi_temp
      - /etc/nginx/dhparam
      - /etc/nginx/conf.d
      - /var/run
      - /tmp
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - NET_BIND_SERVICE
      - SETGID
      - SETUID

  whoami:
    # alpine
    image: "jwilder/whoami@sha256:c621c699e1becc851a27716df9773fa9a3f6bccb331e6702330057a688fd1d5a"
    container_name: whoami
    read_only: true
    cap_drop:
      - ALL
    networks:
      - whoami
    expose:
      - "8000"
    user: nobody
    environment:
      - NETWORK_ACCESS=internal
      - VIRTUAL_HOST=whoami.erdos.local
      - VIRTUAL_PORT=8000


  transmission-movies:
    container_name: transmission-movies
    # alpine
    image: lscr.io/linuxserver/transmission@sha256:f5b529e157669ee98d98ac0aae25bcb6b46ff6ee0e48f59cc9d1fa851cf69ee9
    networks:
      - transmission-movies
      - jackett
    restart: always
    cap_drop:
      - ALL
    cap_add:
      - SETUID
      - SETGID
      - CHOWN
    environment:
      - NETWORK_ACCESS=internal
      - S6_READ_ONLY_ROOT=1
      - PUID=64999
      - PGID=64999
      - VIRTUAL_HOST=movies.erdos.local
      - VIRTUAL_PORT=9091
    expose:
      - "9091" # webui
    ports:
      - "41412:51413/tcp" # p2p traffic
      - "41412:51413/udp" # p2p traffic
    volumes:
      - /docker/data/transmission-movies:/config
      - /docker/media/movies:/downloads/complete
      - transmission-movies-downloads-incomplete:/downloads/incomplete
    tmpfs:
      - /var/run/s6:rw,exec
  
  
  transmission-tv:
    container_name: transmission-tv
    # alpine
    image: lscr.io/linuxserver/transmission@sha256:f5b529e157669ee98d98ac0aae25bcb6b46ff6ee0e48f59cc9d1fa851cf69ee9
    cap_drop:
      - ALL
    cap_add:
      - SETUID
      - SETGID
      - CHOWN
    networks:
      - transmission-tv
    restart: always
    environment:
      - NETWORK_ACCESS=internal
      - S6_READ_ONLY_ROOT=1
      - PUID=64999
      - PGID=64999
      - VIRTUAL_HOST=tv.erdos.local
      - VIRTUAL_PORT=9091
    expose:
      - "9091" # webui
    ports:
      - "41413:51413/tcp" # p2p traffic
      - "41413:51413/udp" # p2p traffic
    volumes:
      - /docker/data/transmission-tv:/config
      - /docker/media/tv:/downloads/complete
      - transmission-tv-downloads-incomplete:/downloads/incomplete
    tmpfs:
      - /var/run/s6:rw,exec

  

  transmission-books:
    container_name: transmission-books
    # alpine
    image: lscr.io/linuxserver/transmission@sha256:f5b529e157669ee98d98ac0aae25bcb6b46ff6ee0e48f59cc9d1fa851cf69ee9
    cap_drop:
      - ALL
    cap_add:
      - SETUID
      - SETGID
      - CHOWN
    networks:
      - transmission-books
    restart: always
    environment:
      - NETWORK_ACCESS=internal
      - S6_READ_ONLY_ROOT=1
      - PUID=64999
      - PGID=64999
      - VIRTUAL_HOST=books.erdos.local
      - VIRTUAL_PORT=9091
    expose:
      - 9091 # webui
    ports:
      - "41414:51413/tcp" # p2p traffic
      - "41414:51413/udp" # p2p traffic
    volumes:
      - /docker/data/transmission-books:/config
      - /docker/media/books:/downloads/complete
      - transmission-books-downloads-incomplete:/downloads/incomplete
    tmpfs:
      - /var/run/s6:rw,exec



  # movie player
  # @TODO try to put this in bridge networking?
  plex:
    container_name: plex
    image: linuxserver/plex:latest
    network_mode: host
    cap_drop:
      - ALL
    cap_add:
      - SETGID
      - SETUID
      - CHOWN
        #read_only: true
    environment:
      - NETWORK_ACCESS=internal
      - S6_READ_ONLY_ROOT=1 # https://github.com/just-containers/s6-overlay/pull/176
      - PUID=64999
      - PGID=64999
      - VERSION=docker
      - ADVERTISE_IP=http://10.0.1.10:32400/
    volumes:
      - /docker/data/plex/database:/config
      - /docker/media/tv:/downloaded_media/tv:ro
      - /docker/media/movies:/downloaded_media/movies:ro
    tmpfs:
      - /var/run/s6:exec
      - /app
      - /defaults


  # Manages your movie library
  # @TODO pin down basic hardening
  radarr:
    image: lscr.io/linuxserver/radarr
    container_name: radarr
    networks:
      - radarr
      - jackett
      - transmission-movies
        #cap_drop:
        #  - ALL
        #cap_add:
        #  - SETUID
        #  - SETGID
        #  - CHOWN
    environment:
      - NETWORK_ACCESS=internal
      - PUID=64999
      - PGID=64999
      - TZ=Europe/London
      - VIRTUAL_HOST=radarr.erdos.local
      - VIRTUAL_PORT=7878
    volumes:
      - /docker/data/raddarr/config:/config
      - /docker/media/movies:/movies
    expose:
      - 7878 
        #ports:
        #- 7878:7878
    restart: unless-stopped


  # Manages your TV library
  sonarr:
    image: lscr.io/linuxserver/sonarr
    container_name: sonarr
    networks:
      - sonarr
      - jackett
      - transmission-tv
    environment:
      - NETWORK_ACCESS=internal
      - PUID=64999
      - PGID=64999
      - TZ=Europe/London
      - VIRTUAL_HOST=sonarr.erdos.local
      - VIRTUAL_PORT=8989
    volumes:
      - /docker/data/sonarr/config:/config
      - /docker/media/tv:/tv
        #- /path/to/downloadclient-downloads:/downloads #optional
    expose:
      - 8989
        #ports:
        #- 8989:8989
    restart: unless-stopped


  jackett:
    image: lscr.io/linuxserver/jackett
    container_name: jackett
    volumes:
      - /docker/data/jackett/config:/config
        #- <path to blackhole>:/downloads
    networks:
      - jackett
      - sonarr
      - radarr
    environment:
      - NETWORK_ACCESS=internal
      - PUID=64999
      - PGID=64999
      - TZ=Europe/London
      - AUTO_UPDATE=true #optional
      - VIRTUAL_HOST=jackett.erdos.local
      - VIRTUAL_PORT=9117
    expose: 
      - 9117


  bazarr:
    image: lscr.io/linuxserver/bazarr
    container_name: bazarr
    networks:
      - proxy
      - bazarr
    environment:
      - NETWORK_ACCESS=internal
      - PUID=64999
      - PGID=64999
      - TZ=Europe/London
      - VIRTUAL_HOST=bazarr.erdos.local
      - VIRTUAL_PORT=6767
    volumes:
      - /docker/data/bazarr/config:/config
      - /docker/media/tv:/tv
      - /docker/media/movies:/movies
    expose:
      - 6767
    restart: always


  ombi:
    #image: lscr.io/linuxserver/ombi
    image: linuxserver/ombi
    container_name: ombi
    networks: 
      - ombi
      - proxy
    environment:
      - NETWORK_ACCESS=internal
      - PUID=64999
      - PGID=64999
      - TZ=Europe/London
        #- BASE_URL=/ombi #optional
      - VIRTUAL_HOST=ombi.erdos.local
      - VIRTUAL_PORT=3579
    volumes:
      - /docker/data/ombi/config:/config
    expose: 
      - 3579
    restart: unless-stopped

# @TODO
# ADD THIS SERVICE
# ADD THIS SERVICE
# Traktarr: Add content to Radarr/Sonarr from Trakt.tv
# https://hub.docker.com/r/containrrr/watchtower
# organizr/organizr
# ADD THIS SERVICE
# ADD THIS SERVICE
# @TODO


volumes:
  transmission-movies-downloads-incomplete:
  transmission-tv-downloads-incomplete:
  transmission-books-downloads-incomplete:

  transmission-vpn-movies-downloads-incomplete:
  transmission-vpn-tv-downloads-incomplete:

  # BOBARR
  web_build:
  api_build:
  api_node_modules:
  web_node_modules:
  db_data:
  redis_data:
  # BOBARR

networks:
  transmission-movies:
  transmission-tv:
  transmission-books:
  jackett:
  sonarr:
  radarr:
  organizr:
    #plex:
  wireguard:
  transmission-vpn-movies:
  transmission-vpn-tv:
  proxy:
  whoami:
  plex:
  bazarr:
  ombi:
