---

# notes
# ports are exposed to the host machine
# exposed only allows access by linked services
#
# EXAMPLE DEPLOYS
# https://gist.github.com/Webreaper/81ecda3ecc45fa61a16dfc90cfc4550d
# EXAMPLE DEPLOYS

# CAP_ADD/DROP information: http://rhelblog.redhat.com/2016/10/17/secure-your-containers-with-this-one-weird-trick/

# @TODO: wireguard, flexget, git server, backblaze, anonaddy
# @TODO review these https://teddit.net/r/radarr/comments/hbwnb2/a_list_of_all_companion_tools_and_software/
# @TODO actually restrict networks

# p2p related apps: https://teddit.net/r/radarr/comments/hbwnb2/a_list_of_all_companion_tools_and_software/
#


version: "2.4"

services:

  nginx-proxy:
    image: jwilder/nginx-proxy
    #image: nginxproxy/nginx-proxy:latest
    #image: nginxproxy/nginx-proxy:alpine
    container_name: proxy
    networks:
      - whoami
      - transmission-movies
      - transmission-tv
      - transmission-books
      # @TODO  plex??????
      - plex
      - radarr
      - sonarr
      - organizr
      - jackett
      - bazarr
      - ombi
    environment:
      - DEFAULT_HOST=whoami.erdos.local
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro

  whoami:
    image: jwilder/whoami
    container_name: whoami
    networks:
      - whoami
    expose:
      - "8000"
    environment:
      - VIRTUAL_HOST=whoami.erdos.local
      - VIRTUAL_PORT=8000


  transmission-movies:
    container_name: transmission-movies
    image: lscr.io/linuxserver/transmission:latest
    #network_mode: service:temp_expressvpn
    networks:
      - transmission-movies
      - jackett
    restart: always
    #read_only: true
    environment:
      #- S6_READ_ONLY_ROOT=1
      - PUID=64999
      - PGID=64999
      - VIRTUAL_HOST=movies.erdos.local
      - VIRTUAL_PORT=9091
    expose:
      - "9091" # webui
    ports:
      #- "49091:9091/tcp"   # webui
      - "41412:51413/tcp" # p2p traffic
      - "41412:51413/udp" # p2p traffic
    volumes:
      - /docker/data/transmission-movies:/config
      - /docker/media/movies:/downloads/complete
      - transmission-movies-downloads-incomplete:/downloads/incomplete
    tmpfs:
      - /var:rw,exec
  
  
  transmission-tv:
    container_name: transmission-tv
    image: lscr.io/linuxserver/transmission:latest
    networks:
      - transmission-tv
    restart: always
    #read_only: true
    #user: abc
    environment:
      #- S6_READ_ONLY_ROOT=1
      - PUID=64999
      - PGID=64999
      - VIRTUAL_HOST=tv.erdos.local
      - VIRTUAL_PORT=9091
    expose:
      - "9091" # webui
    ports:
      #- "49092:9091/tcp"   # webui
      - "41413:51413/tcp" # p2p traffic
      - "41413:51413/udp" # p2p traffic
    volumes:
      - /docker/data/transmission-tv:/config
      - /docker/media/tv:/downloads/complete
      - transmission-tv-downloads-incomplete:/downloads/incomplete
    tmpfs:
      - /var:rw,exec
  

  transmission-books:
    container_name: transmission-books
    image: lscr.io/linuxserver/transmission:latest
    networks:
      - transmission-books
    restart: always
    #read_only: true
    environment:
      - S6_READ_ONLY_ROOT=1
      - PUID=64999
      - PGID=64999
      - VIRTUAL_HOST=books.erdos.local
      - VIRTUAL_PORT=9091
    expose:
      - 9091 # webui
    ports:
      #- "49092:9091/tcp"   # webui
      - "41414:51413/tcp" # p2p traffic
      - "41414:51413/udp" # p2p traffic
    volumes:
      - /docker/data/transmission-books:/config
      - /docker/media/books:/downloads/complete
      - transmission-books-downloads-incomplete:/downloads/incomplete
    tmpfs:
      - /var:rw,exec



  # movie player
  # @TODO try to put this in bridge networking?
  plex:
    container_name: plex
    image: linuxserver/plex:latest
    network_mode: host
    environment:
      - S6_READ_ONLY_ROOT=1 # https://github.com/just-containers/s6-overlay/pull/176
      - PUID=64999
      - PGID=64999
      - VERSION=docker
      - ADVERTISE_IP=http://10.0.1.10:32400/
    volumes:
      - /docker/data/plex/database2:/config
      - /docker/media/tv:/downloaded_media/tv:ro
      - /docker/media/movies:/downloaded_media/movies:ro
    tmpfs:
      - /var:rw,exec


  # Manages your movie library
  radarr:
    image: lscr.io/linuxserver/radarr
    container_name: radarr
    networks:
      - radarr
      - jackett
      - transmission-movies
    environment:
      - PUID=64999
      - PGID=64999
      - TZ=Europe/London
      - VIRTUAL_HOST=radarr.erdos.local
      - VIRTUAL_PORT=7878
    volumes:
      - /docker/data/raddarr/config:/config
      - /docker/media/movies:/movies
        #- /path/to/downloadclient-downloads:/downloads #optional
    expose:
      - 7878 
        #ports:
        #- 7878:7878
    restart: unless-stopped


  # Manages your TV library
  sonarr:
    image: lscr.io/linuxserver/sonarr
    container_name: sonarr
    networks:
      - sonarr
      - jackett
      - transmission-tv
    environment:
      - PUID=64999
      - PGID=64999
      - TZ=Europe/London
      - VIRTUAL_HOST=sonarr.erdos.local
      - VIRTUAL_PORT=8989
    volumes:
      - /docker/data/sonarr/config:/config
      - /docker/media/tv:/tv
        #- /path/to/downloadclient-downloads:/downloads #optional
    expose:
      - 8989
        #ports:
        #- 8989:8989
    restart: unless-stopped


  jackett:
    image: lscr.io/linuxserver/jackett
    container_name: jackett
    volumes:
      - /docker/data/jackett/config:/config
        #- <path to blackhole>:/downloads
    networks:
      - jackett
      - sonarr
      - radarr
    environment:
      - PUID=64999
      - PGID=64999
      - TZ=Europe/London
      - AUTO_UPDATE=true #optional
      - VIRTUAL_HOST=jackett.erdos.local
      - VIRTUAL_PORT=9117
    expose: 
      - 9117


  bazarr:
    image: lscr.io/linuxserver/bazarr
    container_name: bazarr
    networks:
      - proxy
      - bazarr
    environment:
      - PUID=64999
      - PGID=64999
      - TZ=Europe/London
      - VIRTUAL_HOST=bazarr.erdos.local
      - VIRTUAL_PORT=6767
    volumes:
      - /docker/data/bazarr/config:/config
      - /docker/media/tv:/tv
      - /docker/media/movies:/movies
    expose:
      - 6767
    restart: always


  ombi:
    #image: lscr.io/linuxserver/ombi
    image: linuxserver/ombi
    container_name: ombi
    networks: 
      - ombi
      - proxy
    environment:
      - PUID=64999
      - PGID=64999
      - TZ=Europe/London
        #- BASE_URL=/ombi #optional
      - VIRTUAL_HOST=ombi.erdos.local
      - VIRTUAL_PORT=3579
    volumes:
      - /docker/data/ombi/config:/config
    expose: 
      - 3579
    restart: unless-stopped

# @TODO
# ADD THIS SERVICE
# ADD THIS SERVICE
# Traktarr: Add content to Radarr/Sonarr from Trakt.tv
# https://hub.docker.com/r/containrrr/watchtower
# organizr/organizr
# ADD THIS SERVICE
# ADD THIS SERVICE
# @TODO


volumes:
  transmission-movies-downloads-incomplete:
  transmission-tv-downloads-incomplete:
  transmission-books-downloads-incomplete:

  transmission-vpn-movies-downloads-incomplete:
  transmission-vpn-tv-downloads-incomplete:

  # BOBARR
  web_build:
  api_build:
  api_node_modules:
  web_node_modules:
  db_data:
  redis_data:
  # BOBARR

networks:
  transmission-movies:
  transmission-tv:
  transmission-books:
  jackett:
  sonarr:
  radarr:
  organizr:
    #plex:
  wireguard:
  transmission-vpn-movies:
  transmission-vpn-tv:
  proxy:
  whoami:
  plex:
  bazarr:
  ombi:
