---
#
version: "3.7"

services:

  #caddy-tailscale:
  #  build:
  #    context: ./dockerfiles/caddy-tailscale
  #    dockerfile: Dockerfile
  #  env_file: ./dockerfiles/caddy-tailscale/values.env
  #  networks:
  #    - caddy-tailscale-test
  #    #entrypoint: sh /usr/bin/start.sh 





  whoami-svc:
    image: ghcr.io/markpash/tailscale-sidecar:latest
    read_only: true
    networks:
      - whoami
    environment:
      - TS_AUTHKEY=${TS_AUTHKEY}
      - TS_SIDECAR_NAME=whoami
      - TS_SOCKET=/var/run/tailscale/tailscaled.sock
    volumes:
      - whoami-tailscale-config:/home/nonroot
      - ${TS_SIDECAR_BINDINGS_LHS}/whoami.bindings.json:${TS_SIDECAR_BINDINGS_RHS}:ro


  transmission-svc:
    image: ghcr.io/markpash/tailscale-sidecar:latest
    networks:
      - transmission
    environment:
      - TS_AUTHKEY=${TS_AUTHKEY}
      - TS_SIDECAR_STATEDIR=/home/nonroot/tsstate
      - TS_SIDECAR_NAME=transmission
      - TS_SOCKET=/var/run/tailscale/tailscaled.sock
    volumes:
      #- transmission-tailscale-config:/home/nonroot
      - ${TS_SIDECAR_BINDINGS_LHS}/transmission.bindings.json:${TS_SIDECAR_BINDINGS_RHS}:ro
        #entrypoint: tailscale serve https / http://transmission:9091
  
  radarr-svc:
    image: ghcr.io/markpash/tailscale-sidecar:latest
    networks:
      - radarr
    environment:
      - TS_AUTHKEY=${TS_AUTHKEY}
      - TS_SIDECAR_NAME=radarr
    volumes:
      - radarr-tailscale-config:/home/nonroot
      - ${TS_SIDECAR_BINDINGS_LHS}/radarr.bindings.json:${TS_SIDECAR_BINDINGS_RHS}:ro
  
  sonarr-svc:
    image: ghcr.io/markpash/tailscale-sidecar:latest
    networks:
      - sonarr
    environment:
      - TS_AUTHKEY=${TS_AUTHKEY}
      - TS_SIDECAR_NAME=sonarr
    volumes:
      - sonarr-tailscale-config:/home/nonroot
      - ${TS_SIDECAR_BINDINGS_LHS}/sonarr.bindings.json:${TS_SIDECAR_BINDINGS_RHS}:ro
  
  
  
  
#  tdarr-svc:
#    image: ghcr.io/markpash/tailscale-sidecar:latest
#    networks:
#      - tdarr
#    environment:
#      - TS_AUTHKEY=${TS_AUTHKEY}
#      - TS_SIDECAR_NAME=tdarr
#    volumes:
#      - tdarr-tailscale-config:/home/nonroot
#      - ${TS_SIDECAR_BINDINGS_LHS}/tdarr.bindings.json:${TS_SIDECAR_BINDINGS_RHS}:ro
  
  prowlarr-svc:
    image: ghcr.io/markpash/tailscale-sidecar:latest
    networks:
      - prowlarr
    environment:
      - TS_AUTHKEY=${TS_AUTHKEY}
      - TS_SIDECAR_NAME=prowlarr
    volumes:
      - prowlarr-tailscale-config:/home/nonroot
      - ${TS_SIDECAR_BINDINGS_LHS}/prowlarr.bindings.json:${TS_SIDECAR_BINDINGS_RHS}:ro
  
  
  bazarr-svc:
    image: ghcr.io/markpash/tailscale-sidecar:latest
    networks:
      - bazarr
    environment:
      - TS_AUTHKEY=${TS_AUTHKEY}
      - TS_SIDECAR_NAME=bazarr
        #- TS_SIDECAR_STATEDIR=
    volumes:
      - bazarr-tailscale-config:/home/nonroot
      - ${TS_SIDECAR_BINDINGS_LHS}/bazarr.bindings.json:${TS_SIDECAR_BINDINGS_RHS}:ro
  
  
  
  overseerr-svc:
    image: ghcr.io/markpash/tailscale-sidecar:latest
    networks:
      - overseerr
    environment:
      - TS_AUTHKEY=${TS_AUTHKEY}
      - TS_SIDECAR_NAME=overseerr
    volumes:
      - overseerr-tailscale-config:/home/nonroot
      - ${TS_SIDECAR_BINDINGS_LHS}/overseerr.bindings.json:${TS_SIDECAR_BINDINGS_RHS}:ro
  
  flaresolverr-svc:
    image: ghcr.io/markpash/tailscale-sidecar:latest
    networks:
      - flaresolverr
    environment:
      - TS_AUTHKEY=${TS_AUTHKEY}
      - TS_SIDECAR_NAME=flaresolverr
    volumes:
      - flaresolverr-tailscale-config:/home/nonroot
      - ${TS_SIDECAR_BINDINGS_LHS}/flaresolverr.bindings.json:${TS_SIDECAR_BINDINGS_RHS}:ro
  
  
        #  plex-svc:
        #    image: ghcr.io/markpash/tailscale-sidecar:latest
        #    network_mode: host
        #    environment:
        #      - TS_AUTHKEY=${TS_AUTHKEY}
        #      - TS_SIDECAR_NAME=plex
        #    volumes:
        #      - plex-tailscale-config:/home/nonroot
        #      - ${TS_SIDECAR_BINDINGS_LHS}/plex.bindings.json:${TS_SIDECAR_BINDINGS_RHS}:ro
 
   
  dsm-svc:
    image: ghcr.io/markpash/tailscale-sidecar:latest
    network_mode: host
    environment:
      - TS_AUTHKEY=${TS_AUTHKEY}
      - TS_SIDECAR_NAME=dsm
    volumes:
      - dsm-tailscale-config:/home/nonroot
      - ${TS_SIDECAR_BINDINGS_LHS}/dsm.bindings.json:${TS_SIDECAR_BINDINGS_RHS}:ro

  portainer-svc:
    image: ghcr.io/markpash/tailscale-sidecar:latest
    networks: 
      - portainer
    environment:
      - TS_AUTHKEY=${TS_AUTHKEY}
      - TS_SIDECAR_NAME=portainer
    volumes:
      - portainer-tailscale-config:/home/nonroot
      - ${TS_SIDECAR_BINDINGS_LHS}/portainer.bindings.json:${TS_SIDECAR_BINDINGS_RHS}:ro


        #seafile-svc:
        #  image: ghcr.io/markpash/tailscale-sidecar:latest
        #  networks: 
        #    - seafile-svc
        #  environment:
        #    - TS_AUTHKEY=${TS_AUTHKEY}
        #    - TS_SIDECAR_NAME=seafile
        #  volumes:
        #    - seafile-tailscale-config:/home/nonroot
        #    - ${TS_SIDECAR_BINDINGS_LHS}/seafile.bindings.json:${TS_SIDECAR_BINDINGS_RHS}:ro
