# notes
# ports are exposed to the host machine
# exposed only allows access by linked services

# CAP_ADD/DROP information: http://rhelblog.redhat.com/2016/10/17/secure-your-containers-with-this-one-weird-trick/

# @TODO: wireguard, flexget, webdav, git server, backblaze, ansible -- drops caps, restrict permissions, etc.

version: "2.0"

services:

  # downloader
  transmission:
    container_name: transmission
    image: linuxserver/transmission:121
    networks:
      - transmission
    restart: on-failure
    environment:
        - S6_READ_ONLY_ROOT=1 # https://github.com/just-containers/s6-overlay/pull/176
        - VIRTUAL_HOST=movies.oxygen.local
        - VIRTUAL_PORT=9091
        - PUID=64999
        - PGID=64999
    ports:
        - "9091:9091"   # webui
        - "51414:51413/tcp" # p2p traffic
        - "51414:51413/udp" # p2p traffic
    volumes:
      - transmission_config:/config
      - transmission_downloads_complete:/downloads/complete
      - transmission_downloads_incomplete:/downloads/incomplete

  # tv watcher
  radarr:
    container_name: radarr
    image: linuxserver/radarr:version-3.0.0.4235
    environment:
      - PUID=64999
      - PGID=64999
    ports:
      - 7878:7878
    volumes:
      - radarr_config:/config
      - radarr_movies:/movies
      - radarr_downloads:/downloads
    networks:
      - radarr
    restart: on-failure
    #

  # movie watcher
  couch_potato:
    container_name: couch_potato
    image: linuxserver/couchpotato:version-7260c12f
    networks:
      - couch_potato
    restart: on-failure
    environment:
      - PUID=64999
      - PGID=64999
    ports:
      - "5050:5050"
    volumes:
      #- couch_potato_data:/datadir
      #- couch_potato_media:/media
      - couch_potato_config:/config
      - couch_potato_movies:/movies
      - couch_potato_downloads:/downloads


  # movie player
  plex:
    container_name: plex
    image: linuxserver/plex:version-1.21.0.3711-b509cc236
    networks:
      - plex
    restart: on-failure
    environment:
      - PUID=64999
      - PGID=64999
      - VERSION=docker
    volumes:
      - plex_config:/config
      - plex_tv:/tv
      - plex_movies:/movies
    ports:
      - 32400:32400       # (for access to the Plex Media Server) [required]
      - 1900:1900/udp     # UDP: 1900 (for access to the Plex DLNA Server)
        #- 3005:3005         # TCP: 3005 (for controlling Plex Home Theater via Plex Companion)
        #- 5353:5353/udp     # UDP: 5353 (for older Bonjour/Avahi network discovery)
        #- 8324:8324         # TCP: 8324 (for controlling Plex for Roku via Plex Companion)
        #- 32410:32410/udp   # UDP: 32410, 32412, 32413, 32414 (for current GDM network discovery)
        #- 32412:32412/udp   # UDP: 32410, 32412, 32413, 32414 (for current GDM network discovery)
        #- 32413:32413/udp   # UDP: 32410, 32412, 32413, 32414 (for current GDM network discovery)
        #- 32414:32414/udp   # UDP: 32410, 32412, 32413, 32414 (for current GDM network discovery)
      - 32469:32469       # TCP: 32469 (for access to the Plex DLNA Server)



  wireguard_client:
    container_name: wireguard_client
    image: jess/wireguard:latest ###linuxserver/wireguard:version-v1.0.20200827
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    environment:
      - PUID=1000
      - PGID=1000
        #- SERVERURL=wireguard.domain.com #optional
        #- SERVERPORT=51820 #optional
        #- INTERNAL_SUBNET=10.13.13.0 #optional
        #- ALLOWEDIPS=0.0.0.0/0 #optional
    volumes:
      #- wireguard_client_config:/config
      - /opt/home_server_docker/wireguard_client/config:/config
      - /lib/modules:/lib/modules:ro
    ports:
      - 51820:51820/udp
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
    restart: unless-stopped



  ## http://tonylawrence.com/posts/unix/synology/free-your-synology-ports/
  #
  #pihole:
  #  container_name: pihole
  #  image: pihole/pihole:latest
  #  hostname: pihole
  #  domainname: oxygen.local              # <-- Update
  #  mac_address: d0:ca:ab:cd:ef:01
  #  networks:
  #    pihole_network:
  #      ipv4_address: 10.0.1.30           # <-- Update
  #  cap_add:
  #    - NET_BIND_SERVICE
  #    - NET_RAW
  #    - NET_ADMIN
  #  cap_drop:
  #    - ALL
  #  dns:
  #    - 127.0.0.1
  #    - 193.138.218.74
  #  volumes:
  #    - /volume1/docker/pihole/configs/pihole/hosts:/etc/hosts:ro
  #    - /volume1/docker/pihole/etc-pihole/:/etc/pihole
  #    - /volume1/docker/pihole/etc-dnsmasq.d/:/etc/dnsmasq.d
  #  tmpfs:
  #    - /tmp
  #  ports:
  #    - 443/tcp
  #    - 53/tcp
  #    - 53/udp
  #    - 67/udp
  #    - 80/tcp
  #  environment:
  #    - VIRTUAL_HOST=pihole.oxygen.local  # <-- Update (match hostname + domainname)
  #    - VIRTUAL_PORT=80
  #    - WEBPASSWORD=""                    # <-- Add password (if required)
  #  restart: unless-stopped



networks:
    transmission:
    radarr:
    couch_potato:
    plex:
      #
      #proxy:
      #dns:
      #flexget:
      #wireguard:
    # http://tonylawrence.com/posts/unix/synology/free-your-synology-ports/
    #    pihole_network:
    #      driver: macvlan
    #      driver_opts:
    #        parent: eth0
    #      ipam:
    #        config:
    #          - subnet: 10.0.1.0/24            # <-- Update
    #            gateway: 10.0.1.1              # <-- Update
    #            ip_range: 10.0.1.192/27        # <-- Update
    #
    #          #    flexget:
    #          #    pihole:
    #          #    syncthing:
    #      #nginx-proxy:
#
volumes:
  #plex:
  transmission_config:
  transmission_downloads_complete:
  transmission_downloads_incomplete:
  radarr_config:
  radarr_movies:
  radarr_downloads:
  couch_potato_config:
  couch_potato_movies:
  couch_potato_downloads:
  plex_config:
  plex_tv:
  plex_movies:
  wireguard_client_config:


