# notes
# ports are exposed to the host machine
# exposed only allows access by linked services

# CAP_ADD/DROP information: http://rhelblog.redhat.com/2016/10/17/secure-your-containers-with-this-one-weird-trick/


version: "2.0"

services:    



  resilio-sync:
    container_name: dc-resilio-sync
    image: resilio/sync:release-2.5.12
    restart: on-failure
    networks:
        - resilio-sync
    ports:
        - "2000:8888"   # webui
        - "55556:55555" # sync traffic
    read_only: true
    #user: nobody
    cap_drop:
        - ALL
    volumes:
        - /volume1/docker/resilio-sync-new/default_folder_location:/mnt/sync
        - /volume1/docker/resilio-sync-new/file_download_location:/root/Resilio Sync


  transmission-videos:
    container_name: dc-transmission-videos
    image: linuxserver/transmission:121
    networks:
        - transmission-videos
    restart: on-failure
    environment:
        - S6_READ_ONLY_ROOT=1 # https://github.com/just-containers/s6-overlay/pull/176
    ports:
        - "2001:9091"   # webui
        - "51413:51413/tcp" # p2p traffic
        - "51413:51413/udp" # p2p traffic
    read_only: true
    #user: nobody
    cap_drop:
        - ALL
    cap_add:
        - setgid
        - setuid
        - chown
    volumes:
        - /volume1/docker/docker-transmission-videos-new/config:/config
        - /volume1/docker/docker-transmission-videos-new/downloads:/downloads
    tmpfs:
        - /var:rw,exec 
        - /run



networks:
    resilio-sync:
    transmission-videos:

