---

version: "3.7"

services:

  #proxy:
  #  # @TODO split into two containers: https://github.com/nginx-proxy/nginx-proxy#separate-containers
  #  image: jwilder/nginx-proxy:alpine # alpine latest image
  #  #image: nginxproxy/nginx-proxy
  #    #read_only: true
  #  tmpfs:
  #    - /etc/nginx/dhparam/
  #    - /var/cache/nginx/client_temp/
  #    - /var/cache/nginx/proxy_temp/
  #    - /var/cache/nginx/fastcgi_temp/
  #    - /var/cache/nginx/uwsgi_temp/
  #    - /var/cache/nginx/scgi_temp/
  #    - /var/run/
  #    - /etc/nginx/conf.d/
  #    - /etc/nginx/certs/
  #    - /tmp
  #  cap_drop:
  #    - all
  #  cap_add:
  #    - net_bind_service  # for access to port 80 (<1024)
  #    - chown             # @TODO fix this in forked dockerfile
  #    - setgid            # @TODO fix this in forked dockerfile
  #    - setuid            # @TODO fix this in forked dockerfile
  #  environment:
  #    - DEFAULT_HOST=whoami.nas.stonecat-shark.ts.net
  #  ports:
  #    # https://tonylawrence.com/posts/unix/synology/freeing-port-80/
  #    - 9980:80
  #    - 9999:80
  #  volumes:
  #    - /var/run/docker.sock:/tmp/docker.sock:ro
  #    - ${SERVICES}/nginx-proxy/certs:/etc/nginx/certs:ro
  #  restart: always
  #whoami:
  #  image: tailscale/tailscale
  #    #networks:
  #    #  - whoami
  #  environment:
  #    - TS_AUTHKEY=${TS_AUTHKEY}
  #    - TS_SIDECAR_NAME=whoami-new
  #      TS_ACCEPT_DNS=true
  #      TS_HOSTNAME=whoami-test
  #      #network_mode: service:whoami
  #  command: /usr/local/bin/containerboot && tailscale -socket=/tmp/tailscaled.sock serve https / text:"Hello, world!"



      #  whoami:
      #    image: containous/whoami
      #    network_mode: service:whoami-ts
      #      #networks:
      #      #  whoami:
      #      #  apps:
      #      #    aliases:
      #      #      - whoami
      #      #    expose:
      #      #      - 80

  transmission:
    image: haugene/transmission-openvpn
      #network_mode: "service:test"
      #network_mode: "service:transmission"
    networks:
      transmission:
      apps:
        aliases:
          - transmission
    cap_drop:
      - ALL
    cap_add:
      - net_admin     # DOCUMENTED REQUIREMENT
      - mknod         # ALLOWS CREATION OF TUN/TAP IN /dev/net/tun
      - net_raw       # FOR PING IN HEALTHCHECK
      - setgid        # @TODO REVOLVE THIS WITH A FORKED DOCKERFILE
      - dac_override  # @TODO HIGH VULN, FIX WITH FORKED DOCKERFILE
      - setuid
    tmpfs:
      - /tmp
      - /config # data is copied to here
    volumes:
        #- ${TRANSMISSION_DATA}/data/transmission-home:/data/transmission-home
      - ${TRANSMISSION_DATA}/data:/data # @TODO: NEW DEFAULT DIR: /config/transmission-home
      - ${HARDLINK_MEDIA}:/media-organized
      # > openvpn-pre-start.sh copies the on-disk readonly openvpn config to a directory where it is modified
      # > by this container/service. It is not desirable to have these changes written back to disk.
      # > I much prefer having the modifications done from a pristine config every time
      - ${VPN_DATA}/config/openvpn-pre-start.sh:/scripts/openvpn-pre-start.sh:ro
      - ${VPN_DATA}/config/mullvad_userpass.txt:/config/openvpn-credentials.txt:ro
      - ${VPN_DATA}/config/mullvad_ch_zrh.ovpn:/readonly_vpn_config.ovpn:ro
    environment:
      - NETWORK_ACCESS=internal
      - VIRTUAL_HOST=transmission.${LOCAL},trans.${LOCAL},trans.nas.ts
      - VIRTUAL_PORT=9091
      - OPENVPN_PROVIDER=custom
      - OPENVPN_CONFIG=vpn_config
      - LOCAL_NETWORK=192.168.12.0/24
      - TRANSMISSION_PEER_PORT=56004
      - TRANSMISSION_PORT_FORWARDING_ENABLED=true
      - TRANSMISSION_ENCRYPTION=1 # prefer encrypted connections but not required
      - TRANSMISSION_PREFETCH_ENABLED=true
      - DROP_DEFAULT_ROUTE=true # maybe works, maybe breaks
      - LOG_TO_STDOUT=true
        #- PUID="${PUID}"
        #- PGID="${PGID}"
        #labels:
        #  caddy: transmission.caddy.local
        #  caddy.reverse_proxy: "{{upstreams 9091}}"
        #expose:
        #- 9091
    ports:
      - 9091:9091
    sysctls:
      - "net.ipv6.conf.all.disable_ipv6=0"
    restart: always
  

  # @TODO try to put this in bridge networking
  plex:
    image: lscr.io/linuxserver/plex:latest
      #networks:
      #plex-lan:
      #ipv4_address: 10.0.0.30
      #mac_address: 02-42-0a-00-00-1e
    network_mode: host
    environment:
      #- NETWORK_ACCESS=internal
      - PUID="${PUID}"
      - PGID="${PGID}"
      - VERSION=docker
        #- ADVERTISE_IP=http://192.168.12.184:32400/
        #- ADVERTISE_IP=http://plex.${LOCAL}:32400/
      #- ALLOWED_NETWORKS=192.168.12.0/8  #192.168.1.0/24
      - TZ="${TZ}"
    volumes:
      - ${PLEX_DATA}/config:/config
        #- ${PLEX_DATA}/movies-handbrake-encodes:/movies-handbrake-encodes:ro
        #- ${PLEX_DATA}/tv-handbrake-encodes:/tv-handbrake-encodes:ro

      - ${SONARR_DATA}/media-organized:/tv-organized
      - ${HARDLINK_MEDIA}/sonarr-media:/tv-organized-hardlink

      - ${RADARR_DATA}/media-organized:/movies-organized
      - ${HARDLINK_MEDIA}/radarr-media:/movies-organized-hardlink
    expose:
      - 32400
    tmpfs:
      - /tmp
        #tmpfs:
        #  - /var/run/s6:exec
        #  - /app
        #  - /defaults
    restart: always

 
  radarr:
    image: lscr.io/linuxserver/radarr:latest
    networks:
      radarr:
      apps:
        aliases:
          - radarr
      #user: '1026'
    tmpfs:
      #- /var/run/s6:exec,rw
      - /tmp
    cap_drop:
      - all
    cap_add:
      - setgid        # @TODO REVOLVE THIS WITH A FORKED DOCKERFILE
      - setuid
      - chown # @TODO fix this in forked dockerfile
    environment:
      - S6_READ_ONLY_ROOT=1
      - S6_BEHAVIOUR_IF_STAGE2_FAILS=2
      - PUID="${PUID}"
      - PGID="${PGID}"
      - TZ="${TZ}"
      - VIRTUAL_HOST=radarr.${LOCAL},movies.${LOCAL}
      - VIRTUAL_PORT=7878
    volumes:
      - ${RADARR_DATA}/config:/config
      - ${HARDLINK_MEDIA}:/media-organized
        #- ${SHARED_RADARR_DATA}:/data/media-organized
        #- ${SHARED_RADARR_DATA}/media-recycling-bin:/data/media-recycling-bin
        #- ${SHARED_TRANSMISSION_DATA}:/data/completed/
    expose:
      - 7878
    restart: always
  
  

  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    networks:
      sonarr:
      apps:
        aliases:
          - sonarr
    cap_drop:
      - all
    cap_add:
      - setgid
      - setuid
      - chown
    tmpfs:
      #- /var/run/s6:exec,rw
      - /tmp
    environment:
      #- S6_READ_ONLY_ROOT=1
      - NETWORK_ACCESS=internal
      - PUID="${PUID}"
      - PGID="${PGID}"
      - TZ="${TZ}"
      - VIRTUAL_HOST=sonarr.${LOCAL},tv.${LOCAL},sonarr.nas.ts
      - VIRTUAL_PORT=8989
    volumes:
      - ${SONARR_DATA}/config:/config
      - ${HARDLINK_MEDIA}:/media-organized
        #- ${SONARR_DATA}/media-organized:/data/media-organized
        #- ${SONARR_DATA}/media-recycling-bin:/data/media-recycling-bin
        #- ${TRANSMISSION_DATA}/data/completed:/data/completed
    expose:
      - 8989
    restart: always


#  tdarr:
#    image: ghcr.io/haveagitgat/tdarr:latest
#    restart: always
#    networks:
#      tdarr:
#      apps:
#        aliases:
#          - tdarr
#    ports:
#      - 8266:8266 # server port
#    environment:
#      - TZ="${TZ}"
#        #- PUID=${PUID}
#        #- PGID="${PGID}"${PGID}
#      - UMASK_SET=002
#      - serverIP=0.0.0.0
#      - serverPort=8266
#      - webUIPort=8265
#      - internalNode=false
#      - inContainer=true
#      - nodeName=NotANode
#      - NETWORK_ACCESS=internal
#      - VIRTUAL_HOST=tdarr.${LOCAL},transcode.${LOCAL}
#      - VIRTUAL_PORT=8265
#    volumes:
#      - ${TDARR_DATA}/app/server:/app/server
#      - ${TDARR_DATA}/app/configs:/app/configs
#      - ${TDARR_DATA}/app/logs:/app/logs
#        #- /media:/media
#        #- /transcode_cache:/temp
  

  prowlarr:
    image: lscr.io/linuxserver/prowlarr:develop
    networks:
      prowlarr:
      apps:
        aliases:
          - prowlarr
    environment:
      - PUID="${PUID}"
      - PGID="${PGID}"
      - S6_READ_ONLY_ROOT=1
      - NETWORK_ACCESS=internal
      - VIRTUAL_HOST=prowlarr.${LOCAL}
      - VIRTUAL_PORT=9696
      - TZ="${TZ}"
    expose: 
      - 9696
    volumes:
      - ${PROWLARR_DATA}/config:/config
    tmpfs:
      - /tmp
    restart: always


  bazarr:
    image: lscr.io/linuxserver/bazarr:latest
    networks:
      bazarr:
      apps:
        aliases:
          - bazarr
    environment:
      - NETWORK_ACCESS=internal
      - PUID="${PUID}"
      - PGID="${PGID}"
      - TZ=${TZ}
      - VIRTUAL_HOST=subs.${LOCAL},subtitles.${LOCAL},bazarr.${LOCAL},subtitles.${LOCAL}
      - VIRTUAL_PORT=6767
    cap_drop:
      - all
    cap_add:
      - setgid
      - setuid
      - chown
    volumes:
      - ${BAZARR_DATA}/config:/config
      - ${BAZARR_DATA}/downloaded_subtitles:/subtitles
      - ${SONARR_DATA}/media-organized:/tv
      - ${RADARR_DATA}/media-organized:/movies
    tmpfs:
      - /tmp
    expose:
      - 6767
    restart: always

 
  overseerr:
    image: lscr.io/linuxserver/overseerr:latest
    networks:
      overseerr:
      apps:
        aliases:
          - overseer
    environment:
      - NETWORK_ACCESS=internal
      - PUID="${PUID}"
      - PGID="${PGID}"
      - TZ="${TZ}"
      - VIRTUAL_HOST=overseerr.${LOCAL},requests.${LOCAL}
      - VIRTUAL_PORT=5055
    volumes:
      - ${OVERSEERR_DATA}/config:/config
    tmpfs:
      - /tmp
    expose:
      - 5055
    restart: always
  
 
  # Bypasses Cloud Flare
  flaresolverr:
    image: ghcr.io/flaresolverr/flaresolverr:v1.2.9 # prowlerr does not support v2
    user: "nobody:nobody"
    networks:
      flaresolverr:
      apps:
        aliases:
          - flarsolverr
    read_only: true
    cap_drop:
      - ALL
    tmpfs:
      - /tmp
    environment:
      - NETWORK_ACCESS=internal
        #- CAPTCHA_SOLVER=anticaptcha
        #- ANTI_CAPTCHA_APIKEY=123456789
      - TZ="${TZ}"
      - VIRTUAL_HOST=flaresolverr.${LOCAL},flare.${LOCAL}
      - VIRTUAL_PORT=8191
    expose:
      - 8191
    restart: always
  

      #  readarr:
      #    image: lscr.io/linuxserver/readarr:develop
      #    networks:
      #      readarr:
      #      apps:
      #        aliases:
      #          - radarr
      #    environment:
      #      - PUID="${PUID}"
      #      - PGID="${PGID}"
      #      - TZ="${TZ}"
      #      - NETWORK_ACCESS=internal
      #      - VIRTUAL_HOST=readarr.${LOCAL},read.${LOCAL},books.${LOCAL}
      #      - VIRTUAL_PORT=8787
      #    volumes:
      #      - ${READARR_DATA}/config:/config
      #      - ${READARR_DATA}/books:/books:ro
      #        #  - ${SERVICES}/transmission/data/completed:/downloads:ro
      #    restart: unless-stopped
 

  recyclarr:
    image: ghcr.io/recyclarr/recyclarr
    user: 1000:1000
    networks: 
      - recyclarr
    volumes:
      #- ${RECYCLARR_DATA}/config:/config
      - ${RECYCLARR_DATA}:/recyclarr_data
    environment:
      - TZ="${TZ}"
      - RECYCLARR_CREATE_CONFIG=true
        




  seafile-db:
    image: mariadb:10.6
    environment:
      - MYSQL_ROOT_PASSWORD=${SEAFILE_DB_ROOT_PASSWORD} # Requested, set the root's password of MySQL service. CHANGE ON FIRST LOGIN
      - MYSQL_LOG_CONSOLE=true
    volumes:
      - ${SEAFILE_DATA}/var/lib/mysql:/var/lib/mysql  # Requested, specifies the path to MySQL data persistent store.
      #- tmp-seafile-db:/var/lib/mysql  # Requested, specifies the path to MySQL data persistent store.
    networks:
      seafile:
        aliases:
          - db # default used by seafile image

  seafile-cache:
    image: memcached:1.6.18
    entrypoint: memcached -m 256
    networks:
      seafile:
        aliases:
          - memcached # default used by seafile image
          
  seafile:
    image: seafileltd/seafile-mc:latest
    ports:
      - "9980:80"
#     - "443:443"  # If https is enabled, cancel the comment.
    volumes:
      - ${SEAFILE_DATA}/shared:/shared   # Requested, specifies the path to Seafile data persistent store.
        #- tmp-seafile:/shared   # Requested, specifies the path to Seafile data persistent store.
    environment:
      - DB_HOST=db
      - DB_ROOT_PASSWD=${SEAFILE_DB_ROOT_PASSWORD}  # Requested, the value should be root's password of MySQL service.
      - TIME_ZONE=${TZ}  # Optional, default is UTC. Should be uncomment and set to your local time zone.
      - SEAFILE_ADMIN_EMAIL=${SEAFILE_ADMIN_EMAIL} # Specifies Seafile admin user, default is 'me@example.com'.
      - SEAFILE_ADMIN_PASSWORD=${SEAFILE_ADMIN_PASSWORD} # Specifies Seafile admin password, default is 'asecret'.
      - SEAFILE_SERVER_LETSENCRYPT=false   # Whether to use https or not.
      - SEAFILE_SERVER_HOSTNAME=seafile.stonecat-shark.ts.net # Specifies your host name if https is enabled.
        #    healthcheck:
        #      test: wget --no-verbose --tries=1 --spider http://localhost
    depends_on:
      seafile-db:
        condition: service_started
      seafile-cache:
        condition: service_started
    networks:
      - seafile
      - seafile-svc
