---
version: "3.7"

services:


  sab-tailscale:
    image: lscr.io/linuxserver/baseimage-alpine@sha256:97cd98ace665f7e1be4a83d0c4b960ae320779b99c9a1d572da6a680041c1b7d
    restart: always
    network_mode: host
    environment:
      - TZ=${TZ}
      - PUID=${PUID}
      - PGID=${PGID}
      - TAILSCALE_HOSTNAME=sab
      - DOCKER_MODS=${TAILSCALE_DOCKER_MOD}
      - TAILSCALE_USE_SSH=${TAILSCALE_USE_SSH}
      - TAILSCALE_AUTHKEY=${TAILSCALE_AUTHKEY}
      - TAILSCALE_SERVE_PORT=${SABNZBD_EXTERNAL_PORT}
      - TAILSCALE_STATE_DIR=${TAILSCALE_STATE_DIR}
      - TAILSCALE_SERVE_MODE=${TAILSCALE_SERVE_MODE}
    volumes:
      - tailscale-sabnzbd-vpn:${TAILSCALE_STATE_DIR}
    tmpfs:
      - /tmp
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - SETGID
      - SETUID


  qb-tailscale:
    image: lscr.io/linuxserver/baseimage-alpine@sha256:97cd98ace665f7e1be4a83d0c4b960ae320779b99c9a1d572da6a680041c1b7d
    restart: always
    network_mode: host
    environment:
      - TZ=${TZ}
      - PUID=${PUID}
      - PGID=${PGID}
      - TAILSCALE_HOSTNAME=qb
      - DOCKER_MODS=${TAILSCALE_DOCKER_MOD}
      - TAILSCALE_USE_SSH=${TAILSCALE_USE_SSH}
      - TAILSCALE_AUTHKEY=${TAILSCALE_AUTHKEY}
      - TAILSCALE_SERVE_PORT=${QBITTORRENT_PORT}
      - TAILSCALE_STATE_DIR=${TAILSCALE_STATE_DIR}
      - TAILSCALE_SERVE_MODE=${TAILSCALE_SERVE_MODE}
    volumes:
      - tailscale-qbittorrentvpn:${TAILSCALE_STATE_DIR}
    tmpfs:
      - /tmp
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - SETGID
      - SETUID


  dsm-tailscale:
    image: lscr.io/linuxserver/baseimage-alpine@sha256:97cd98ace665f7e1be4a83d0c4b960ae320779b99c9a1d572da6a680041c1b7d
    restart: always
    network_mode: host
    environment:
      - TZ=${TZ}
      - PUID=${PUID}
      - PGID=${PGID}
      - TAILSCALE_HOSTNAME=dsm
      - TAILSCALE_SERVE_PORT=${DSM_PORT}                            # moved from 8080/8443 to 48080/48443 because conflicts with qbittorrent
      - DOCKER_MODS=${TAILSCALE_DOCKER_MOD}
      - TAILSCALE_USE_SSH=${TAILSCALE_USE_SSH}
      - TAILSCALE_AUTHKEY=${TAILSCALE_AUTHKEY}
      - TAILSCALE_STATE_DIR=${TAILSCALE_STATE_DIR}
      - TAILSCALE_SERVE_MODE=${TAILSCALE_SERVE_MODE}
    volumes:
      - tailscale-dsm:${TAILSCALE_STATE_DIR}
    tmpfs:
      - /tmp
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - SETGID
      - SETUID
