---
version: "3.7"

# OFFICIAL: https://tailscale.dev/blog/docker-mod-tailscale
# UNofficial: docker + tailscale: https://mrpowergamerbr.com/us/blog/2023-03-20-untangling-your-network-tailscale-in-docker-compose/

# TRASH GUIDES: https://trash-guides.info
# TG / RECYCLARR: https://recyclarr.dev/wiki/

# DEFUALT CAPABILITIES
# - KILL
# - CHOWN
# - MKNOD
# - SETGID
# - SETUID
# - FSETID
# - FOWNER
# - NET_RAW
# - SETFCAP
# - SETPCAP
# - SYS_CHROOT
# - AUDIT_WRITE
# - DAC_OVERRIDE
# - NET_BIND_SERVICE


# mitigate top-level dir mounting to support hardlinks
# - /data/media/tv                                      # . mitigate top-level dir mounting
# - /data/media/music                                   # .
# - /data/media/movies                                  # .
#                                                       # .
# - /data/torrents/tv                                   # .
# - /data/torrents/music                                # .
# - /data/torrents/movies                               # .
# - /data/torrents/incomplete                           # .
#                                                       # .
# - /data/usenet/incomplete                             # .
# - /data/usenet/complete/tv                            # .
# - /data/usenet/complete/music                         # .
# - /data/usenet/complete/movies                        # /

services:

  plex:
    image: lscr.io/linuxserver/plex@sha256:3bc1444e7e8a91dfa0735b1878b4f0eb39c680e97ed419149f74ef24cd1c9222
    restart: unless-stopped
    environment:
      - TZ=${TZ}
      - PUID=${PUID}
      - PGID=${PGID}
      - VERSION=docker
      - TAILSCALE_HOSTNAME=plex
      - PLEX_CLAIM=${PLEX_CLAIM:-''}
      - TAILSCALE_SERVE_PORT=${PLEX_PORT}
      - DOCKER_MODS=${TAILSCALE_DOCKER_MOD}
      - TAILSCALE_AUTHKEY=${TAILSCALE_AUTHKEY}
      - TAILSCALE_USE_SSH=${TAILSCALE_USE_SSH}
      - TAILSCALE_STATE_DIR=${TAILSCALE_STATE_DIR}
      - TAILSCALE_SERVE_MODE=${TAILSCALE_SERVE_MODE}
    volumes:
      - ${PLEX_APP_DATA}/config:/config
      - ${MEDIA_DIRPATH}/media/tv:/tv:ro
      - tailscale-plex:${TAILSCALE_STATE_DIR}
      - ${MEDIA_DIRPATH}/media/music:/music:ro
      - ${MEDIA_DIRPATH}/media/movies:/movies:ro
    tmpfs:
      - /tmp
    networks:
      - plex
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - SETGID
      - SETUID
      - FOWNER                                              # "... Permission denied (/var/lib/apt ..." and others
      - DAC_OVERRIDE



  radarr:
    image: lscr.io/linuxserver/radarr@sha256:16c446007ee5e34283073abf3642ae9ef3da4a2124a21d8459fff2828bc84c35
    restart: unless-stopped
    environment:
      - TZ=${TZ}
      - PGID=${PGID}
      - PUID=${PUID}
      - TAILSCALE_HOSTNAME=radarr
      - DOCKER_MODS=${TAILSCALE_DOCKER_MOD}
      - TAILSCALE_SERVE_PORT=${RADARR_PORT}
      - TAILSCALE_AUTHKEY=${TAILSCALE_AUTHKEY}
      - TAILSCALE_USE_SSH=${TAILSCALE_USE_SSH}
      - TAILSCALE_STATE_DIR=${TAILSCALE_STATE_DIR}
      - TAILSCALE_SERVE_MODE=${TAILSCALE_SERVE_MODE}
    volumes:
      - ${MEDIA_DIRPATH}:/data                              # mount top-level dir to support hardlinks and atomic moves
                                                            # /data/media/movies; /data/torrents/movies; /data/usenet/movies;
      - ${RADARR_APP_DATA}/config:/config
      - tailscale-radarr:${TAILSCALE_STATE_DIR}
    tmpfs:
      - /tmp
      - /data/media/tv                                      # . mitigate top-level dir mounting
      - /data/media/music                                   # .
      # /data/media/movies                                  # .
      #                                                     # .
      - /data/torrents/tv                                   # .
      - /data/torrents/music                                # .
      # /data/torrents/movies                               # .
      - /data/torrents/incomplete                           # .
                                                            # .
      - /data/usenet/incomplete                             # .
      - /data/usenet/complete/tv                            # .
      - /data/usenet/complete/music                         # .
      # /data/usenet/complete/movies                        # /
    networks:
      - bazarr
      - doplarr
      - sabnzbd
      - prowlarr
      - overseerr
      - recyclarr
      - qbittorrent
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - SETGID
      - SETUID


  sonarr:
    image: lscr.io/linuxserver/sonarr@sha256:bc957613c6d15f18ac2ee1532d81de390532f16208dd9c66e0cac5c1e38b3abf
    restart: unless-stopped
    environment:
      - TZ=${TZ}
      - PUID=${PUID}
      - PGID=${PGID}
      - TAILSCALE_HOSTNAME=sonarr
      - DOCKER_MODS=${TAILSCALE_DOCKER_MOD}
      - TAILSCALE_SERVE_PORT=${SONARR_PORT}
      - TAILSCALE_USE_SSH=${TAILSCALE_USE_SSH}
      - TAILSCALE_AUTHKEY=${TAILSCALE_AUTHKEY}
      - TAILSCALE_STATE_DIR=${TAILSCALE_STATE_DIR}
      - TAILSCALE_SERVE_MODE=${TAILSCALE_SERVE_MODE}
    volumes:
      - ${MEDIA_DIRPATH}:/data                              # mount top-level dir to support hardlinks and atomic moves
                                                            # /data/media/tv; /data/torrents/tv; /data/usenet/tv;
      - ${SONARR_APP_DATA}/config:/config
      - tailscale-sonarr:${TAILSCALE_STATE_DIR}
    tmpfs:
      - /tmp
      # /data/media/tv                                      # . mitigate top-level dir mounting
      - /data/media/music                                   # .
      - /data/media/movies                                  # .
      #                                                     # .
      # /data/torrents/tv                                   # .
      - /data/torrents/music                                # .
      - /data/torrents/movies                               # .
      - /data/torrents/incomplete                           # .
                                                            # .
      - /data/usenet/incomplete                             # .
      # /data/usenet/complete/tv                            # .
      - /data/usenet/complete/music                         # .
      - /data/usenet/complete/movies                        # /
    networks:
      - bazarr
      - sabnzbd
      - doplarr
      - prowlarr
      - overseerr
      - recyclarr
      - qbittorrent
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - SETGID
      - SETUID


  lidarr:
    image: lscr.io/linuxserver/lidarr@sha256:6e6175ecc3b82a1a7715ff31e473e07e7d8582a10cf6b482546a2cf437412801
    restart: unless-stopped
    environment:
      - TZ=${TZ}
      - PUID=${PUID}
      - PGID=${PGID}
      - TAILSCALE_HOSTNAME=lidarr
      - DOCKER_MODS=${TAILSCALE_DOCKER_MOD}
      - TAILSCALE_SERVE_PORT=${LIDARR_PORT}
      - TAILSCALE_USE_SSH=${TAILSCALE_USE_SSH}
      - TAILSCALE_AUTHKEY=${TAILSCALE_AUTHKEY}
      - TAILSCALE_STATE_DIR=${TAILSCALE_STATE_DIR}
      - TAILSCALE_SERVE_MODE=${TAILSCALE_SERVE_MODE}
    volumes:
      - ${MEDIA_DIRPATH}:/data                              # mount top-level dir to support hardlinks and atomic moves
                                                            # /data/media/music; /data/torrents/music; /data/usenet/music;
      - ${LIDARR_APP_DATA}/config:/config
      - tailscale-lidarr:${TAILSCALE_STATE_DIR}
    tmpfs:
      - /tmp
    networks:
      - sabnzbd
      - prowlarr
      - qbittorrent
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - SETGID
      - SETUID


  prowlarr:
    image: lscr.io/linuxserver/prowlarr@sha256:2d0051afebfbf95953d5a9b886ed0e63403d8c6742816ace35011b73c9482a59
    restart: unless-stopped
    environment:
      - TZ=${TZ}
      - PUID=${PUID}
      - PGID=${PGID}
      - TAILSCALE_HOSTNAME=prowlarr
      - DOCKER_MODS=${TAILSCALE_DOCKER_MOD}
      - TAILSCALE_SERVE_PORT=${PROWLARR_PORT}
      - TAILSCALE_USE_SSH=${TAILSCALE_USE_SSH}
      - TAILSCALE_AUTHKEY=${TAILSCALE_AUTHKEY}
      - TAILSCALE_STATE_DIR=${TAILSCALE_STATE_DIR}
      - TAILSCALE_SERVE_MODE=${TAILSCALE_SERVE_MODE}
    volumes:
      - ${PROWLARR_APP_DATA}/config:/config
      - tailscale-prowlarr:${TAILSCALE_STATE_DIR}
    tmpfs:
      - /tmp
    networks:
      - prowlarr
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - SETGID
      - SETUID


  bazarr:
    image: lscr.io/linuxserver/bazarr@sha256:2886d8946830b6772b82e4533cd32265233d90c053ac2118cc5216726ddc5e38
    restart: unless-stopped
    environment:
      - TZ=${TZ}
      - PUID=${PUID}
      - PGID=${PGID}
      - TAILSCALE_HOSTNAME=bazarr
      - DOCKER_MODS=${TAILSCALE_DOCKER_MOD}
      - TAILSCALE_SERVE_PORT=${BAZARR_PORT}
      - TAILSCALE_USE_SSH=${TAILSCALE_USE_SSH}
      - TAILSCALE_AUTHKEY=${TAILSCALE_AUTHKEY}
      - TAILSCALE_STATE_DIR=${TAILSCALE_STATE_DIR}
      - TAILSCALE_SERVE_MODE=${TAILSCALE_SERVE_MODE}
    volumes:
      - ${MEDIA_DIRPATH}:/data                              # mount top-level dir to support hardlinks and atomic moves
                                                            # /data/media/movies; /data/media/tv;
      - ${BAZARR_APP_DATA}/config:/config
      - tailscale-bazarr:${TAILSCALE_STATE_DIR}
    tmpfs:
      - /tmp
    networks:
      - bazarr
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - SETGID
      - SETUID


  qb:
    image: binhex/arch-qbittorrentvpn@sha256:8a1f48298f08f07fc701f5347e3b33ecd3a5b2ffc1e459f8f0fea90f956114eb
    # image: binhex/asch-qbittorrentvpn:4.6.0-1-01                 # required to set initial webui password due to bug
    restart: unless-stopped
    environment:
      - TZ=${TZ}
      - PUID=${PUID}
      - PGID=${PGID}
      - VPN_ENABLED=yes
      - WEBUI_PORT=${QBITTORRENT_PORT}
      - VPN_PROV=${BINHEX_VPN_PROVIDER}
      - VPN_CLIENT=${BINHEX_VPN_CLIENT}
      - LAN_NETWORK=${BINHEX_LAN_NETWORK}
      - NAME_SERVERS=${BINHEX_NAME_SERVERS}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${QBITTORRENT_APP_DATA}/data:/data
      - ${QBITTORRENT_APP_DATA}/config:/config
      - ${MEDIA_DIRPATH}/torrents:/data/torrents                  # torrent downloads go here
      - ${QBITTORRENT_USER_DATA}/airvpn-config:/config/openvpn:ro # "sed: couldn't open temporary file /config/openvpn/sed<random>: Read-only file system"
    tmpfs:
      - /tmp
    networks:
      - qbittorrent
    ports:                                                        # https://docs.docker.com/network/#published-ports
      - 127.0.0.1:8080:${QBITTORRENT_PORT}                        # bind to host loopback
    cap_drop:
      - ALL
    devices:
      - /dev/net/tun:/dev/net/tun
    cap_add:
      - CHOWN
      - SETGID
      - SETUID
      # - MKNOD                                                   # create tun device if not mounted from host
      - NET_RAW                                                   # "can't initialize iptables table `filter': Permission denied"
      - NET_ADMIN                                                 # required to establish vpn tunnel


  sab:
    image: binhex/arch-sabnzbdvpn@sha256:63d868d66cc6775a13458ee30d97ae69ade34dd50a5b8e27d05742fb165ab3a1
    restart: unless-stopped
    environment:
      - TZ=${TZ}
      - PUID=${PUID}
      - PGID=${PGID}
      - VPN_ENABLED=yes
      - VPN_PROV=${BINHEX_VPN_PROVIDER}
      - VPN_CLIENT=${BINHEX_VPN_CLIENT}
      - LAN_NETWORK=${BINHEX_LAN_NETWORK}
      - NAME_SERVERS=${BINHEX_NAME_SERVERS}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${SABNZBD_APP_DATA}/config:/config
      - ${MEDIA_DIRPATH}/usenet:/data/usenet                            # nzb downloads go here
      - ${SABNZBD_USER_DATA}/scripts:/scripts:ro,exec
      - ${QBITTORRENT_USER_DATA}/airvpn-config:/config/openvpn:ro       # "sed: couldn't open temporary file /config/openvpn/sed<random>: Read-only file system"
    tmpfs:
      - /tmp
    networks:
      - sabnzbd
    ports:
      - 127.0.0.1:${SABNZBD_EXTERNAL_PORT}:${SABNZBD_INTERNAL_PORT}     # bind to host loopback
    cap_drop:
      - ALL
    devices:
      - /dev/net/tun:/dev/net/tun
    cap_add:
      - CHOWN                                                           # chown: changing ownership of '/usr/...': Operation not permitted
      - SETGID                                                          # couldn't setuid to 65534: Could not set groups of effective user
      - SETUID                                                          # child process was not spawned
      # - MKNOD                                                         # create tun device if not mounted from host
      - NET_RAW                                                         # iptables v1.8.10 (legacy): can't initialize iptables table `filter'
      - NET_ADMIN                                                       # required to establish vpn tunnel


  overseerr:
    image: lscr.io/linuxserver/overseerr@sha256:884c81c4f8c173cc22098a4cf8f2db27f353a7d6c9979f64dbe67d91ff1fb1b3
    restart: unless-stopped
    environment:
      - TZ=${TZ}
      - PUID=${PUID}
      - PGID=${PGID}
      - TAILSCALE_HOSTNAME=overseerr
      - DOCKER_MODS=${TAILSCALE_DOCKER_MOD}
      - TAILSCALE_SERVE_PORT=${OVERSEERR_PORT}
      - TAILSCALE_USE_SSH=${TAILSCALE_USE_SSH}
      - TAILSCALE_AUTHKEY=${TAILSCALE_AUTHKEY}
      - TAILSCALE_STATE_DIR=${TAILSCALE_STATE_DIR}
      - TAILSCALE_SERVE_MODE=${TAILSCALE_SERVE_MODE}
    volumes:
      - ${OVERSEERR_APP_DATA}/config:/config
      - tailscale-overseerr:${TAILSCALE_STATE_DIR}
    tmpfs:
      - /tmp
    networks:
      - plex
      - overseerr
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - SETGID
      - SETUID


  doplarr:
    image: lscr.io/linuxserver/doplarr@sha256:6bc06d8de0fc030eae9ce1635f944cbbfef851a7582ee41ad2a884d76b6fcf23
    restart: unless-stopped
    environment:
      - TZ=${TZ}
      - PUID=${PUID}
      - PGID=${PGID}
      - LOG_LEVEL=:info                               # optional
      - PARTIAL_SEASONS=true                          # optional
      - DISCORD__MAX_RESULTS=25                       # optional
      - SONARR__API=${SONARR_API_KEY}
      - RADARR__API=${RADARR_API_KEY}
      - RADARR__URL=http://radarr:7878
      - SONARR__URL=http://sonarr:8989
      - DISCORD__TOKEN=${DISCORD_TOKEN}
      - DISCORD__REQUESTED_MSG_STYLE=:plain           # optional
      - SONARR__QUALITY_PROFILE=Recyclarr | Default
      - RADARR__QUALITY_PROFILE=Recyclarr | Default
    volumes:
      - ${DOPLARR_APP_DATA}/config:/config
    tmpfs:
      - /tmp
    networks:
      - doplarr
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - SETGID
      - SETUID


  plex-meta-manager:
    image: lscr.io/linuxserver/plex-meta-manager@sha256:fcd2557ea45b44472369faac1066b5179dd4d6f498d0fd2dc29ef89785a23cd3
    #image: meisnate12/plex-meta-manager
    restart: no
    environment:
      - TZ=${TZ}
      - PUID=${PUID}
      - PGID=${PGID}
      - PMM_RUN=False                               # set to 'True' to execute immediately
      - PMM_TIME=06:00                              # run after plex nightly schedule
      - PMM_NO_MISSING=true
      - PMM_DELETE_COLLECTIONS=False                # set to 'True' to clear all collections before running
    volumes:
      - ${PLEX_META_MANAGER_APP_DATA}/config:/config
    tmpfs:
      - /tmp
    networks:
      - plex
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - SETGID
      - SETUID


  # SYNC TRASH GUIDES SETTINGS (AND OTHERS) TO SONARR AND RADARR
  recyclarr:
    image: ghcr.io/recyclarr/recyclarr@sha256:02add40feae0569401b5020528e06419b47046723d0bb4bef1e82325e9eefdad
    restart: unless-stopped
    read_only: true
    user: ${PUID}:${PGID}
    environment:
      - TZ=${TZ}
      - RECYCLARR_CREATE_CONFIG=true
    volumes:
      - ${RECYCLARR_APP_DATA}/config:/config
    tmpfs:
      - /tmp
    networks:
      - recyclarr
    cap_drop:
      - ALL
