---


version: "2.4"
services: 


  caddy-formatter:
    image: caddy:2.7.3
    network_mode: none
    restart: no
    read_only: true
    cap_drop:
      - ALL
    cap_add:
      - DAC_OVERRIDE
      - NET_BIND_SERVICE
    volumes:
      - ${CADDY_DATA}/etc/caddy/Caddyfile:/etc/caddy/Caddyfile
    entrypoint: caddy fmt --overwrite /etc/caddy/Caddyfile



  caddy:
    image: my_caddy #caddy:2.7.3-alpine
    build:
      context: ./dockerfiles/caddy
      dockerfile: ./dockerfiles/caddy/Dockerfile
    restart: unless-stopped
    depends_on:
      caddy-formatter:
        condition: service_completed_successfully
    networks:
      - caddy
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    expose:
      - 2019 # admin hub
    tmpfs:
      - /config
        #- /data #@ MOVE THIS BACK TO VOLUMES
    volumes:
      - ${CADDY_DATA}/etc/caddy/Caddyfile:/etc/caddy/Caddyfile #:ro
        #- ${CADDY_DATA}/srv:/srv
      - ${CADDY_DATA}/data:/data
        #- ${CADDY_DATA}/usr/share/caddy/index.html:/usr/share/caddy/index.html:ro

  whoami:
    image: containous/whoami
    networks:
      - caddy
    expose:
      - 80
        #labels:
        #  caddy: whoami.nas.stonecat-shark.ts.net
        #  caddy.reverse_proxy: "{{upstreams 80}}"


volumes:
  tailscaled:

networks:
  #exit-node:
  caddy:
    external: true
      #name: nas_caddy
