---
version: "2.4"
# notes
# ports are exposed to the host machine
# exposed only allows access by linked services
#
# EXAMPLE DEPLOYS
# https://gist.github.com/Webreaper/81ecda3ecc45fa61a16dfc90cfc4550d
# EXAMPLE DEPLOYS

# CAP_ADD/DROP information: http://rhelblog.redhat.com/2016/10/17/secure-your-containers-with-this-one-weird-trick/

# @TODO review these https://teddit.net/r/radarr/comments/hbwnb2/a_list_of_all_companion_tools_and_software/
# @TODO try https://dockersl.im
# @TODO run containers as non-root
# @TODO https://github.com/HaveAGitGat/Tdarr
# @TODO https://github.com/TheUltimateC0der/Listrr
# @TODO off-load plex trasncoding https://github.com/UnicornTranscoder/UnicornTranscoder

# p2p related apps: https://teddit.net/r/radarr/comments/hbwnb2/a_list_of_all_companion_tools_and_software/
#


version: "2.4"

services:

  # media player
  # @TODO try to put this in bridge networking
  plex:
    image: lscr.io/linuxserver/plex:latest
    networks:
      plex:
        ipv4_address: 10.0.0.4
   # ports:
   #   - "32400:32400"
    environment:
      - PUID=1026
      - PGID=100
      - VERSION=docker
      - TZ=America/New_York
        #deploy:
        #  resources:
        #    reservations:
        #      devices:
        #        - capabilities: [ gpu ]
        #          driver: nvidia
        #          count: all
    volumes:
      - /home/josh/plex_config:/config
      - /mnt/nas_media/docker/apps/sonarr/media-organized:/TV:ro
      - /mnt/nas_media/docker/apps/radarr/media-organized:/MOVIES:ro
      - /dev/shm:/transcode  # default ramdisk that uses a maximum 50% of RAM
    tmpfs:
      - /tmp
    restart: always

volumes:
  plex_config_volume:

networks:
  plex:
    name: plex
    driver: macvlan
    driver_opts:
      parent: eno1
    ipam:
      driver: default
      config:
        - subnet: "10.0.0.0/29"
          gateway: "10.0.0.1"
