---
version: "2.4"
# notes
# ports are exposed to the host machine
# exposed only allows access by linked services
#
# EXAMPLE DEPLOYS
# https://gist.github.com/Webreaper/81ecda3ecc45fa61a16dfc90cfc4550d
# EXAMPLE DEPLOYS

# CAP_ADD/DROP information: http://rhelblog.redhat.com/2016/10/17/secure-your-containers-with-this-one-weird-trick/

# @TODO review these https://teddit.net/r/radarr/comments/hbwnb2/a_list_of_all_companion_tools_and_software/
# @TODO try https://dockersl.im
# @TODO run containers as non-root
# @TODO https://github.com/HaveAGitGat/Tdarr
# @TODO https://github.com/TheUltimateC0der/Listrr
# @TODO off-load plex trasncoding https://github.com/UnicornTranscoder/UnicornTranscoder

# p2p related apps: https://teddit.net/r/radarr/comments/hbwnb2/a_list_of_all_companion_tools_and_software/
#


version: "2.4"

services:


  # media player
  # @TODO try to put this in bridge networking
  plex:
    image: lscr.io/linuxserver/plex:latest
    network_mode: host
      #ports:
      #  - "32400:32400"
      #  #- "127.0.0.1:32400:32400"
    environment:
      #- NETWORK_ACCESS=internal
      - PUID=1026
      - PGID=100
      - VERSION=docker
        #- ADVERTISE_IP=http://192.168.12.184:32400/
        #- ADVERTISE_IP=http://plex.pc.local:32400/
        #- ALLOWED_NETWORKS=192.168.12.0/8  #192.168.1.0/24
      - TZ=America/New_York
        #deploy:
        #  resources:
        #    reservations:
        #      devices:
        #        - capabilities: [ gpu ]
        #          driver: nvidia
        #          count: all
    volumes:
      - /home/josh/plex_config:/config
      - /mnt/nas_media/docker/apps/sonarr/media-organized:/TV:ro
      - /mnt/nas_media/docker/apps/radarr/media-organized:/MOVIES:ro
      - /dev/shm:/transcode  # default ramdisk that uses a maximum 50% of RAM
      #- /volume1/data/docker/apps/plex/config:/config
        #- /volume1/data/docker/apps/sonarr/media-organized:/tv-organized:ro
        #- /volume1/data/docker/apps/radarr/media-organized:/movies-organized:ro
    tmpfs:
      - /tmp
        #tmpfs:
        #  - /var/run/s6:exec
        #  - /app
        #  - /defaults
    restart: always

volumes:
  plex_config_volume:


      #networks:
      #  traefik_hub:
